// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// convertDataBack
List convertDataBack(IntegerVector id, NumericVector time, NumericVector amt, NumericVector ii, IntegerVector evid, IntegerVector cmt, int cmtOffset, int linNcmt, int linKa, int neq);
RcppExport SEXP _nlmixr2extra_convertDataBack(SEXP idSEXP, SEXP timeSEXP, SEXP amtSEXP, SEXP iiSEXP, SEXP evidSEXP, SEXP cmtSEXP, SEXP cmtOffsetSEXP, SEXP linNcmtSEXP, SEXP linKaSEXP, SEXP neqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type amt(amtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ii(iiSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type evid(evidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cmt(cmtSEXP);
    Rcpp::traits::input_parameter< int >::type cmtOffset(cmtOffsetSEXP);
    Rcpp::traits::input_parameter< int >::type linNcmt(linNcmtSEXP);
    Rcpp::traits::input_parameter< int >::type linKa(linKaSEXP);
    Rcpp::traits::input_parameter< int >::type neq(neqSEXP);
    rcpp_result_gen = Rcpp::wrap(convertDataBack(id, time, amt, ii, evid, cmt, cmtOffset, linNcmt, linKa, neq));
    return rcpp_result_gen;
END_RCPP
}
// preCondInv
SEXP preCondInv(SEXP Rin);
RcppExport SEXP _nlmixr2extra_preCondInv(SEXP RinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Rin(RinSEXP);
    rcpp_result_gen = Rcpp::wrap(preCondInv(Rin));
    return rcpp_result_gen;
END_RCPP
}
