# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the inverse preconditioning matrix
#'
#' @param Rin The R matrix input
#'
#' @return The inverse preconditioning matrix
#'
preCondInv <- function(Rin) {
    .Call(`_nlmixr2extra_preCondInv`, Rin)
}

