# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convertDataBack <- function(id, time, amt, ii, evid, cmt, cmtDvid, dvidDvid, linNcmt = 0L, linKa = 0L, neq = 0L, replaceEvid = 5L) {
    .Call(`_nlmixr2extra_convertDataBack`, id, time, amt, ii, evid, cmt, cmtDvid, dvidDvid, linNcmt, linKa, neq, replaceEvid)
}

#' Calculate the inverse preconditioning matrix
#'
#' @param Rin The R matrix input
#'
#' @return The inverse preconditioning matrix
#' @noRd
preCondInv <- function(Rin) {
    .Call(`_nlmixr2extra_preCondInv`, Rin)
}

