# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convertDataBack <- function(id, time, amt, ii, evid, cmt, cmtOffset = 0L, linNcmt = 0L, linKa = 0L, neq = 0L) {
    .Call(`_nlmixr2extra_convertDataBack`, id, time, amt, ii, evid, cmt, cmtOffset, linNcmt, linKa, neq)
}

#' Calculate the inverse preconditioning matrix
#'
#' @param Rin The R matrix input
#'
#' @return The inverse preconditioning matrix
#'
preCondInv <- function(Rin) {
    .Call(`_nlmixr2extra_preCondInv`, Rin)
}

